name: PCL CMake Action
description: Action for building PCL-CMake project which depends on vtk-9/qt5
author: Daniel T.

inputs:
  build_type:
    description: "Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)"
    default: "Release"
    required: false
    type: string

runs:
  using: "docker"
  image: docker://danieltobon43/pcl-docker:1.12.1-alpine3.15-All-GA-v1

# https://actions-cool.github.io/github-action-branding/
branding:
  icon: "package"
  color: "gray-dark"
